Invoke make immediately

diff --git a/rjdMake b/rjdMake
--- a/rjdMake
+++ b/rjdMake
@@ -29,10 +29,14 @@ which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected ppc-amigaos cross com
     --disable-shared \
     --without-python \
     --host=ppc-amigaos \
-    CC=ppc-amigaos-g++ \
     CFLAGS="-mcrt=${C_LIB}" \
     CXXLAGS="-mcrt=${C_LIB}" \
     CPPFLAGS="-mcrt=${C_LIB}" \
     LDFLAGS="-mcrt=${C_LIB} -athread=native"
     
-
+if (( !${?} ))
+then
+    make -j$(nproc) || { echo "Error with make" 2>&1 ; exit 1 ; }
+else
+    echo "Error with configure" 2>&1 ; exit 1
+fi
