We are compiling with gcc and getting unresolved symbols when using libicu / libxml2 that were built with the c++ compiler and they were using the way that our current ADTOOLS uses threading -native. -lstdc++ seems to also always resolve to using the .so file in preference, so i have forcefully provided a path to the static libstdc++. This expects that the user has the folder: /sdk/ which is a link to their ADTOOLS installation's SDK

diff --git a/rjdMake b/rjdMake
--- a/rjdMake
+++ b/rjdMake
@@ -22,6 +22,12 @@ function _error
 
 which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected ppc-amigaos cross compiler on the path" 10
 
+if [[ ! -d /sdk/ ]]
+then
+    echo "Error, you do not have a symbolic link named /sdk/ pointing to your ADTOOLS installation SDK" 2>&1
+    exit 3
+fi
+
 # TODO: Remove --without-python. Stupid configuration pkg-config issue.
 ./autogen.sh \
     --prefix="${INSTALL_PREFIX}" \
@@ -32,11 +38,12 @@ which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected ppc-amigaos cross com
     CFLAGS="-mcrt=${C_LIB}" \
     CXXLAGS="-mcrt=${C_LIB}" \
     CPPFLAGS="-mcrt=${C_LIB}" \
-    LDFLAGS="-mcrt=${C_LIB} -athread=native"
+    LDFLAGS="-mcrt=${C_LIB} -athread=native" \
+    LIBS="/sdk/../lib/libstdc++.a -lpthread"
     
 if (( !${?} ))
 then
     make -j$(nproc) || { echo "Error with make" 2>&1 ; exit 1 ; }
 else
-    echo "Error with configure" 2>&1 ; exit 1
+    echo "Error with configure" 2>&1 ; exit 2
 fi
